-- [Veila](https://github.com/naurissteins/Veila) has been removed / replaced with [qylock](https://github.com/Darkkal44/qylock), please set up beforehand, or setup veila on your own.

general {
    lock_cmd = /home/kie/.local/share/quickshell-lockscreen/lock.sh --qylocks logout screen
    before_sleep_cmd = /home/kie/.local/share/quickshell-lockscreen/lock.sh --qylocks logout screen
    after_sleep_cmd = hyprctl dispatch dpms on      # wake display after sleep
    inhibit_sleep = 3
}

# Dim the screen first (optional)
listener {
    timeout = 90                                  # 1.5 minute
    on-timeout = brightnessctl -s set 10%           # set monitor backlight to 10%
    on-resume = brightnessctl -r                    # restore monitor backlight
}

# Lock the screen (Visible)
listener {
    timeout = 120                                   # 2 minutes
    on-timeout = /home/kie/.local/share/quickshell-lockscreen/lock.sh
}

# Turn off the screen (Black out)
listener {
    timeout = 300                                   # 5 minutes (3 mins after locking)
    on-timeout = hyprctl dispatch dpms off          # turn off display
    on-resume = hyprctl dispatch dpms on            # turn on display
}