[background]
mode = "gradient"
color = "#00000000"
scaling = "fill"
dim_strength = 54

[background.gradient]
top_left = "#00000000"
top_right = "#00000000"
bottom_left = "#00000000"
bottom_right = "#00000000"

[[background.outputs]]
name = "DP-1"
path = "/path/to/left.jpg"

[[background.outputs]]
name = "HDMI-A-1"
path = "/path/to/right.jpg"
[battery]
enabled = false

[weather]
enabled = false

[visuals.clock]
enabled = false
format = "12h"
style = "standard"
meridiem_font_size = 22
meridiem_x = 6
meridiem_y = 7
font_family = "SF Pro"
font_weight = 400
color = "rgba(255, 255, 255, 0.81)"
font_size = 88
halign = "center"
valign = "center"
x = 0
y = -60

[visuals.date]
enabled = false
format = "long"
font_family = "SF Pro"
font_weight = 400
color = "rgba(255, 255, 255, 0.81)"
font_size = 22
halign = "center"
valign = "center"
x = 0
y = 0

[visuals.input]
placeholder = "..."
background_color = "rgba(58, 58, 58, 0.6)"
border_width = 3
width = 310
height = 24
radius = 0
mask_color = "#ffffff"
font_family = "SF Pro Display"
font_weight = 500
font_size = 16
halign = "center"
valign = "center"
x = 0
y = 0

[visuals.status]
enabled = false
mode = "inline"
rejected_color = "#2a0000"
pending_color = "#ffffff"

[visuals.eye]
enabled = false
color = "rgba(123, 123, 123, 0.86)"

[visuals.caps_lock]
enabled = false
color = "rgba(255, 255, 255, 0.52)"

[visuals.placeholder]
color = "rgba(255, 255, 255, 0.6)"

[visuals.avatar]
enabled = false
image_path = "/home/key/.config/veila/pfp.jpg"
size = 100

[visuals.username]
enabled = false
x = 0
y = -40

[visuals.keyboard]
enabled = false
background_size = 46
radius = 0
background_color = "rgba(255, 255, 255, 0.05)"
color = "rgba(255, 255, 255, 0.68)"
size = 16
halign = "right"
valign = "top"
x = -24
y = 21

[visuals.battery]
background_color = "rgba(255, 255, 255, 0.05)"
background_size = 46
radius = 0
color = "rgba(255, 255, 255, 0.68)"
size = 20
halign = "right"
valign = "top"
x = -78
y = 21

[visuals.weather.icon]
size = 40
opacity = 80
halign = "left"
valign = "bottom"
x = 40
y = -112

[visuals.weather.temperature]
font_size = 40
font_family = "Geom"
font_weight = 600
letter_spacing = 0
color = "rgba(255, 255, 255, 0.73)"
halign = "left"
valign = "bottom"
x = 40
y = -70

[visuals.weather.location]
font_size = 22
font_family = "SF Pro"
font_weight = 400
color = "rgba(214, 227, 255, 0.58)"
halign = "left"
valign = "bottom"
x = 40
y = -44

[visuals.now_playing]
enabled = false
fade_duration_ms = 320

[visuals.now_playing.artwork]
size = 44
radius = 0
opacity = 90
halign = "left"
valign = "center"
x = 10
y = 0
relative_to = "now_playing"

[visuals.now_playing.artist]
width = 318
color = "rgba(255, 255, 255, 0.39)"
font_family = "SF Pro"
font_size = 16
font_weight = 400
halign = "left"
valign = "top"
x = 65
y = 10
relative_to = "now_playing"

[visuals.now_playing.title]
width = 318
color = "rgba(255, 255, 255, 0.69)"
font_family = "SF Pro"
font_size = 16
font_weight = 400
halign = "left"
valign = "bottom"
x = 65
y = -10
relative_to = "now_playing"

# Now playing backdrop
[[visuals.backdrop]]
enabled = false
name = "now_playing"
show_when = "now_playing"
mode = "blur"
color = "rgba(255, 255, 255, 0.05)"
blur_strength = 12
radius = 0
border_color = "#FFFFFF18"
width = 400
height = 60
halign = "right"
valign = "bottom"
x = -40
y = -40